import { forwardRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useCompoundBody } from "@react-three/cannon";

useGLTF.preload("./models/misc/wheel.glb");

// Auto-generated by: https://github.com/pmndrs/gltfjsx
const Wheel = forwardRef(({ radius = 0.1, leftSide, ...props }, ref) => {
  const { nodes, materials } = useGLTF("./models/misc/wheel.glb");

  useCompoundBody(
    () => ({
      mass: 1,
      type: "Kinematic",
      material: "wheel",
      collisionFilterGroup: 0,
      shapes: [
        {
          type: "Cylinder",
          rotation: [0, 0, -Math.PI / 2],
          args: [0.15, 0.15, 0.2, 16],
        },
      ],
      ...props,
    }),
    ref
  );

  return (
    <group ref={ref}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel.geometry}
        material={materials["Car.001"]}
        scale={0.11}
      />
    </group>
  );
});

export default Wheel;
